name = "StochasticBlockModel"
uuid = "e022115e-0a72-11ea-0a57-4fc90b22dc23"
authors = ["Breno Araujo"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
